### ISSUE TITLE
Adicionar parâmetros para o H2O versão TIP5P-Ew

### ISSUE THREAD

**Issue by lipelopesoliveira** [lipelopesoliveira/ForceFields#1]
### O que deve ser feito?

Adicionar os parâmetros de van der Waals e parâmetros críticos para a água na parametrização `TIP5P-Ew`, adaptado do  [artigo original](https://aip.scitation.org/doi/10.1063/1.1652434).

### Existem requisitos e / ou restrições que devem ser atendidos durante a execução desta tarefa?

- [x] Adicionar os [parâmetros](https://github.com/iRASPA/RASPA2/blob/master/examples/Non-Basic/3_MD_NPT_water/force_field_mixing_rules.def) de van der Waals para o modelo `TIP5P-Ew`;
- [x] Adicionar o [arquivo](https://github.com/iRASPA/RASPA2/blob/master/examples/Non-Basic/3_MD_NPT_water/Tip5p.def) com a definição da molécula na pasta do campo de forças [Generic](https://github.com/lipelopesoliveira/ForceFields/tree/main/Molecules/Generic);
- [x] Editar o arquivo de definição da molécula para incluir as constantes críticas corretas;
- [ ] (Opcional) Fazer um benchmarck com os outros modelos e dados experimentais;

### O que será obtido ao final dessa tarefa?

Um campo de forças com os parâmetros para a água seguindo o modelo `TIP5P-Ew`.

### Mais alguma outra coisa?

Os dados de constantes críticas devem ser retirados [deste](https://pubs.acs.org/doi/full/10.1021/jp0495242) artigo. Note que `TIP5P-Ew` = `TIP5P-E`!

O fator acêntrico pode ser calculado utilizando a equação 

![CodeCogsEqn](https://user-images.githubusercontent.com/33868364/151605790-ec6e94bc-cb6b-4db9-a382-d040dd6f9b52.svg)

com a pressão de saturação sendo calculada utilizando a equação de Antoine:

![CodeCogsEqn(3)](https://user-images.githubusercontent.com/33868364/145873796-0e835e21-05e0-46dd-bca0-c32319b7f080.png)

Com `A`, `B` e `C` sendo as constantes determinadas no artigo.

Fonte: [POLING, Bruce E.; PRAUSNITZ, John M.; O’CONNELL, John P. Properties of gases and liquids. McGraw-Hill Education, 2001.](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjq8bqAqej0AhXVqZUCHahUD8cQFnoECAUQAQ&url=https%3A%2F%2Fwww.eng.uc.edu%2F~beaucag%2FClasses%2FChEThermoBeaucage%2FBooks%2FBruce%2520E.%2520Poling%2C%2520John%2520M.%2520Prausnitz%2C%2520John%2520P.%2520O%2527Connell%2520-%2520The%2520properties%2520of%2520gases%2520and%2520liquids-McGraw-Hill%2520Professional%2520(2000).pdf&usg=AOvVaw3Nu9ghsOKmd2novajJckG8)

**Comment by Joao-mcs** [comment]
Parâmetros que foram modificados. As tabelas foram retiradas do [artigo](https://pubs.acs.org/doi/full/10.1021/jp0495242)
![2021-12-16_11-00](https://user-images.githubusercontent.com/64266425/146387764-c58edbd6-bb9b-4dd7-b2e4-8f6c3f33508e.png)
![2021-12-16_11-01](https://user-images.githubusercontent.com/64266425/146387778-4cc74414-efd9-40c2-88c6-0d7e421db12c.png)

**Comment by lipelopesoliveira** [comment]
```
def psat(T):
    A = 13.642988
    B = -5073.9387
    C = 21.888973
    return np.exp(A + (B/ (T + C)))

def omega(tc):
    return -1 -np.log10(psat(tc*0.7)/psat(tc))

tc = 540.9
omega(tc)
>>> 0.5863502819813085
```
